spring.application.name=choviet

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/choviet

# GraphQL
spring.graphql.schema.locations=classpath:graphql/
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
# http://localhost:8080/graphiql

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=chovietluonma
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=namcao123a@gmail.com
spring.mail.password=xbxy xaji xeyw cknp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Logging Configuration
logging.level.com.ecommerce=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Authorization Configuration - Permissions
authorization.permissions.SUPER_ADMIN.user[0]=CREATE
authorization.permissions.SUPER_ADMIN.user[1]=READ
authorization.permissions.SUPER_ADMIN.user[2]=UPDATE
authorization.permissions.SUPER_ADMIN.user[3]=DELETE
authorization.permissions.SUPER_ADMIN.customer[0]=CREATE
authorization.permissions.SUPER_ADMIN.customer[1]=READ
authorization.permissions.SUPER_ADMIN.customer[2]=UPDATE
authorization.permissions.SUPER_ADMIN.customer[3]=DELETE
authorization.permissions.SUPER_ADMIN.order[0]=CREATE
authorization.permissions.SUPER_ADMIN.order[1]=READ
authorization.permissions.SUPER_ADMIN.order[2]=UPDATE
authorization.permissions.SUPER_ADMIN.order[3]=DELETE
authorization.permissions.SUPER_ADMIN.product[0]=CREATE
authorization.permissions.SUPER_ADMIN.product[1]=READ
authorization.permissions.SUPER_ADMIN.product[2]=UPDATE
authorization.permissions.SUPER_ADMIN.product[3]=DELETE
authorization.permissions.SUPER_ADMIN.news[0]=CREATE
authorization.permissions.SUPER_ADMIN.news[1]=READ
authorization.permissions.SUPER_ADMIN.news[2]=UPDATE
authorization.permissions.SUPER_ADMIN.news[3]=DELETE
authorization.permissions.SUPER_ADMIN.packageservice[0]=CREATE
authorization.permissions.SUPER_ADMIN.packageservice[1]=READ
authorization.permissions.SUPER_ADMIN.packageservice[2]=UPDATE
authorization.permissions.SUPER_ADMIN.packageservice[3]=DELETE
authorization.permissions.SUPER_ADMIN.invoice[0]=CREATE
authorization.permissions.SUPER_ADMIN.invoice[1]=READ
authorization.permissions.SUPER_ADMIN.invoice[2]=UPDATE
authorization.permissions.SUPER_ADMIN.invoice[3]=DELETE
authorization.permissions.SUPER_ADMIN.discount[0]=CREATE
authorization.permissions.SUPER_ADMIN.discount[1]=READ
authorization.permissions.SUPER_ADMIN.discount[2]=UPDATE
authorization.permissions.SUPER_ADMIN.discount[3]=DELETE
authorization.permissions.SUPER_ADMIN.attendance[0]=CREATE
authorization.permissions.SUPER_ADMIN.attendance[1]=READ
authorization.permissions.SUPER_ADMIN.attendance[2]=UPDATE
authorization.permissions.SUPER_ADMIN.attendance[3]=DELETE
authorization.permissions.SUPER_ADMIN.chat[0]=CREATE
authorization.permissions.SUPER_ADMIN.chat[1]=READ
authorization.permissions.SUPER_ADMIN.chat[2]=UPDATE
authorization.permissions.SUPER_ADMIN.chat[3]=DELETE

authorization.permissions.ADMIN.user[0]=CREATE
authorization.permissions.ADMIN.user[1]=READ
authorization.permissions.ADMIN.user[2]=UPDATE
authorization.permissions.ADMIN.user[3]=DELETE
authorization.permissions.ADMIN.customer[0]=CREATE
authorization.permissions.ADMIN.customer[1]=READ
authorization.permissions.ADMIN.customer[2]=UPDATE
authorization.permissions.ADMIN.customer[3]=DELETE

# STAFF - Nhân viên cơ bản
authorization.permissions.STAFF.product[0]=READ
authorization.permissions.STAFF.order[0]=READ
authorization.permissions.STAFF.customer[0]=READ

authorization.permissions.STAFF_MANAGEMENT.user[0]=READ
authorization.permissions.STAFF_MANAGEMENT.user[1]=UPDATE

authorization.permissions.STAFF_CHAT.chat[0]=CREATE
authorization.permissions.STAFF_CHAT.chat[1]=READ
authorization.permissions.STAFF_CHAT.chat[2]=UPDATE
authorization.permissions.STAFF_CHAT.chat[3]=DELETE

authorization.permissions.STAFF_NEWS.news[0]=CREATE
authorization.permissions.STAFF_NEWS.news[1]=READ
authorization.permissions.STAFF_NEWS.news[2]=UPDATE
authorization.permissions.STAFF_NEWS.news[3]=DELETE

# Role Creation Configuration
authorization.role-creation.SUPER_ADMIN[0]=ADMIN
authorization.role-creation.ADMIN[0]=STAFF
authorization.role-creation.ADMIN[1]=STAFF_MANAGEMENT
authorization.role-creation.ADMIN[2]=STAFF_CHAT
authorization.role-creation.ADMIN[3]=STAFF_NEWS












