spring.application.name=choviet

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/choviet

# GraphQL
spring.graphql.schema.locations=classpath:graphql/
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
# http://localhost:8080/graphiql

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=chovietluonma
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=namcao123a@gmail.com
spring.mail.password=xbxy xaji xeyw cknp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true











